### ISSUE TITLE
is_writable on read-only filesystem is a non-sense

### ISSUE THREAD

**Issue by ztec** [doctrine/cache#157] opened 2016-04-19 10:35 UTC
### The story

I use doctrine cache through symfony and i have a read-only filesystem with the following file permission 

```
 -r-xr-xr-x  1 www-data www-data 170434 Apr 19 11:34 folder
 -r--r--r--  1 www-data www-data 170434 Apr 19 11:34 file.ext
```
## Issue

I don't have write permission on files and folder and i got an error in production when i need to load cache through **lib/Doctrine/Common/Cache/FileCache.php**. 

```
Uncaught PHP Exception InvalidArgumentException: \"The directory \"[...]var/cache/prod/annotations\" is not writable.\" at [...]vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php line 92
```

In my case, all cache are created before puting file into production server, so the cache is here and don't need to be generated at runtime. No write permission is fundamentally required.

_Please don't tell anyone but i fixed the issue with ugly hack on my code_
##### Move is_writable out of constructor

I suggest to remove the "**is_writable**" check in the constructor of fileCache : https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/FileCache.php#L91

and to move this check to all "write" actions like it is already done in "_writeFile_" : https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/FileCache.php#L239
##### Use own implementation with RW & RO in symfony

 see https://github.com/doctrine/cache/issues/157#issuecomment-212049742
## Cons
- It may have a BC break on all implementation of the abstract class FileCache because they will need to check write permission if they do file modification themselves.
- Cache object is supposed to be RW (https://github.com/doctrine/cache/issues/157#issuecomment-211883721)
- Make it easy to notice file Permission issue (https://github.com/doctrine/cache/issues/157#issuecomment-211920417)
- Mathematic say you cannot be absolutely sure you won't miss cache (https://github.com/doctrine/cache/issues/157#issuecomment-211921158)
## Pro
- Can use not writable folder to read stored cache file (this all the point of this issue :-) )
## What do you say about it ?

Can you give me opinions and pro/cons you see ?

**Comment by Ocramius** [comment] 2016-04-19 12:02
The check should not be removed. Unless you have a cache object that
supports only read operations (you need to write one that aggregates only
the read operations), the implementation by doctrine is r+w, and should
therefore reject a non-writable dir.

**Comment by ztec** [comment] 2016-04-19 13:16
Yes but i don't have the opportunity to easily change the cache used.

The warmer could use the RW cache and the "user" use a RO cache, but for consistency i would like both to be the same (same code, same behaviors).

I don't say the cache should not be able to write, just that this check should not be in the constructor. 
Because implementing a RO cache with the same behavior is absolutely impossible now (many properties are privates and should be opened to do so) 

I agree about the intention not clear about what will be done with the FileCache but on construct, no intention is made, only when writing/deleting/changing/... stuf. 

In order to keep this idea of RW cache and R cache, a new level of abstraction must be made (maybe two interface RO & RW). This is maybe a bit overkill, don't you think ?

**Comment by Ocramius** [comment] 2016-04-19 13:18
@ztec note that this exception was introduced to ease usage in first place: most bugs related to cache are usually caused by wrong directory permissions.

 > This is maybe a bit overkill, don't you think ? 

No, that's just SRP advantages and disadvantages exposed :-)

**Comment by stof** [comment] 2016-04-19 13:21
@ztec except that there is nothing guaranteeing you that the annotation reader will never write in the cache again. Code using the annotation reader can ask it to read annotations for any reflector out there (class, method, function and maybe even inline doc-comment), so being sure that you never miss the cache is almost impossible.

**Comment by ztec** [comment] 2016-04-19 18:07
@Ocramius lol Yes but this project is not always an example about SRP :-) 

The exception can stay and just be at another place. You can still have the ease of finding that your cache folder is not writable but only when you try to write to it.

@stof I Agree concerning the mathematics logic behind. But in my case, any write to the filesystem lead to a fatal ! (500) 

I consider not writing a cache file as fatal, and when it happen, that mean that cache have not been correctly warmed up and I need to fix it. 
Some people may consider this as a warning and continue there journey without cache file written. (withe performance issue related) 

I think **not being able to write inside a cache directory** not as Fatal as **not being able to alter/create cache** on production runtime. 

The exception raised in constructor make this cache unusable on read-only filesytem because it do not finish it's own initialisation job in such cases. (Catching the exception cannot allow me to ignore it on purpose)

**Comment by Ocramius** [comment] 2016-04-19 18:09
The problem here is that you are re-purposing a general-usage cache for a read-only purpose. 

This component is generic: if you need a read-only cache, then make it a read-only cache that directly throws exceptions on any writes (no checks needed, just replace the function body with a `throw`.

We can't do that for core, but you can write your own tiny adapter (doesn't take much time, really) to do that for your specific use-case.

**Comment by ztec** [comment] 2016-04-19 18:19
In reality, I would like to be able to decorate the original cache directly (because i don't wan to change the way cache file is handled).

I cannot do it right now, and if i want to make change in symfony about that, I would have to re-write the fileCache adapter completely to have coherence between RW cache and RO cache. I find it possible but it's a pity not to use an already existing solution.

**Comment by Ocramius** [comment] 2016-04-19 18:21
I wrote custom caches multiple times: takes a couple hours and is less of a headache compared to reuse.

C&P being perfectly valid here.

**Comment by ztec** [comment] 2016-04-19 18:23
I don't like C&P, but I'll try to push it on Symfony direclty to see opinions.

**Comment by alcaeus** [comment] 2021-05-21 06:19
Closing as we're sunsetting this library. Please see #354 for more details.

**Closed by alcaeus** 2021-05-21 06:19 UTC
