### ISSUE TITLE
Race Condition in RedisCache::doFetchMultiple

### ISSUE THREAD

**Issue by steffenweber** [doctrine/cache#258] opened 2018-05-17 10:10 UTC
RedisCache calls "mget" to fetch multiple values: https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/RedisCache.php#L60

If one of the returned values is false then it double-checks whether the value really doesn't exist by calling the "exists" method on the key. Now, if the value has just been (re-)created between the "mget" and the "exists" call then RedisCache thinks that false really is the value of the specified key (although it isn't, it just called "mget" while the key didn't exist, then later called "exists" after the key was re-added).

I think this is a conceptional issue of letting PhpRedis serialize the data (instead of doing that in the RedisCache library). With serialization enabled, PhpRedis returns false for a) keys that don't exist and b) for keys that exist and have the value false. To distinguish between these two cases, RedisCache uses the "exists" call which unfortunately introduces the described race condition.

I think RedisCache should do the (de-)serialization on its own.

This issue seems to have been introduced in https://github.com/doctrine/cache/commit/47f3e599160fb3fce74072c47649b7dbfdd1e72d.

Reference: https://xenforo.com/community/threads/argument-1-passed-to-xf-template-templater-setgroupstyles-must-be-of-the-type-array.139491/#post-1252143

**Comment by Ocramius** [comment] 2018-05-17 11:59
Is there a way to get a failing test case for this?

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by steffenweber** [comment] 2018-05-17 12:27
```
<?php
require 'vendor/autoload.php';

$redis = new Redis();
$redis->connect('localhost');

$cache = new \Doctrine\Common\Cache\RedisCache();
$cache->setRedis($redis);

while (true)
{
	$cache->save('mykey', 'myvalue');
	$cache->delete('mykey');
}
```

```
<?php
require 'vendor/autoload.php';

$redis = new Redis();
$redis->connect('localhost');

$cache = new \Doctrine\Common\Cache\RedisCache();
$cache->setRedis($redis);

while (true)
{
	var_dump($cache->fetchMultiple(['mykey']));
}
```

Run these two scripts in parallel in two terminal windows.

Script 1 repeatedly sets and deletes "mykey". So "mykey" either doesn't exist or it has the value "myvalue".

Script 2 repeatedly calls "fetchMultiple" to fetch the value of "mykey". It should either return an empty array or an array with key "mykey" and value "myvalue".

What actually happens is that quite frequently it returns an array with key "mykey" and value `false`.

Example output:

```
array(0) {
}
array(1) {
  ["mykey"]=>
  string(7) "myvalue"
}
array(0) {
}
array(1) {
  ["mykey"]=>
  string(7) "myvalue"
}
array(1) {
  ["mykey"]=>
  bool(false)
}
array(1) {
  ["mykey"]=>
  bool(false)
}
...
```

(For some reason, "exists" is only called in "fetchMultiple" / "doFetchMultiple" but not in "fetch" / "doFetch".)

**Comment by Tobion** [comment] 2018-05-17 14:04
Thanks for the detailed description. The described race condition indeed seems possible.
@steffenweber do you have an idea how to solve it?

**Comment by Tobion** [comment] 2018-05-17 14:29
I found a simple solution in #259
Please test if it solves your test case.

**Comment by steffenweber** [comment] 2018-05-17 15:05
Unfortunately, #259 does not help. The key might be gone by the time `$value = $this->redis->get($key);` is called and then `false` is returned (instead of nothing). Running `php script2.php | grep false` still matches lots of lines.

I think the only two options are to either a) remove the "exists" call and disallow using `false` as a value (I doubt that would be acceptable in a general-pupose caching library) or to b) stop using the built-in serialization features of PhpRedis and instead do the serialization in the RedisCache class. Then you can be sure that `false` actually means that a key doesn't exist.

This should work: https://github.com/doctrine/cache/pull/260

**Comment by Xon** [comment] 2018-05-17 16:34
The problem is the 'false' isn't coming from the serialization features of PhpRedis, but from the redis protocol decoding.

The redis protocol returns a special `(nil)` value/type which gets converted to an explicit `false`

**Comment by alcaeus** [comment] 2021-05-21 06:18
Closing as we're sunsetting this library. Please see #354 for more details.

**Closed by alcaeus** 2021-05-21 06:18 UTC
