### ISSUE TITLE
File cache names are too long. Checks limiting it to 255 do not actually work properly in all cases.

### ISSUE THREAD

**Issue by yurii-mysak** [doctrine/cache#176] opened 2016-08-04 14:15 UTC
First of all, there was this issue posted for Symfony here: [https://github.com/symfony/symfony/issues/19363](url) . I encountered the same thing and spent a lot of time investigating it and came up to this: 
When using FileCache filenames sometimes are longer, than supported. I am using docker containers on vagrant with VBox linked shared folders. There is a limit for a `FILE_NAME` of 255 characters. 
I tried renaming some of the long filenames inside cache directories and the error switched to another folder: 
`/var/www/html/var/cache/de~/annotations/fd` -> `var/www/html/var/cache/de~/annotations/44`
for example. So it looks like command is able to process the first folder, but then fails on the second one, as there is also a very long filename (256 characters including extension, which should be 255).

I am using docker containers on vagrant with VirtualBox and I suspect that the vboxsf might have some FILE_NAME or PATH_NAME limitations and those are 255 and 4096 respectively. 

Then I tried to reduce filenames from 256 chars and went to `Doctrine\Common\Cache\FilesystemCache` and changed extension from `.doctrinecache.data` to `.doctrine.data` and everything worked, I was able to clear the cache after clearing the previous one manually (it still had long files).

It led me to suspect, that the problem lies within `Doctrine\Common\Cache\FileCache`, `getFilename()` does not work properly and sometimes has wrong behaviour. I think this issue is also connected to #174 .

IMPORTANT: Issue persists only for Symfony dev environment and works fine for prod.

**Comment by stof** [comment] 2016-08-26 09:59
I have a similar issue on Ubuntu. The annotation cache fails to be written saying

```
rename(<redacted>/app/cache/dev/annotations/aa/swappz9lFr,<redacted>/app/cache/dev/annotations/aa/5b5b435d496e63656e746565765c57656242756e646c655c456e746974795c50726f66696c6524666565644974656d4e6565644d6f6465726174696f6e405b416e6e6f745d5d5b315d.doctrinecache.data): File name too long
```

I'm not using Virtualbox or docker in this project, just running it on my computer directly.

**Comment by TorbenKoehn** [comment] 2016-09-07 10:02
I have the same issue on a simple Ubuntu LTS 16. The home-directory is encrypted by default (which is a good thing, basically).

As I run most of my projects from my projects-folder in my home-directory (Guess I'm not the only one), I get a load of debug-messages while developing (working with Symfony)

**Comment by gadelat** [comment] 2016-10-06 14:36
Same here, except I run the project in docker container, while host has encrypted Ubuntu 14.04 folder.

**Comment by jstuhli** [comment] 2016-12-08 12:53
I'm having issues with using filecache running PHP under docker.
By default docker uses AUFS driver for file storage which has a 242 character limit for FILE_NAME. See http://aufs.sourceforge.net/aufs3/man.html (Search for 242)

Running on ubuntu 14.04
$ getconf  NAME_MAX /
255

Running on ubuntu 14.04 inside docker:
$ getconf  NAME_MAX /
242

It's actually quite easy to reproduce. The following code works on normal linux, but fails when in docker:
```
<?php

require 'vendor/autoload.php';

$cache = new Doctrine\Common\Cache\PhpFileCache('cache');

$size = 113;
$name = str_pad('', $size, 'a');
var_dump($cache->save($name, 123));
var_dump($cache->fetch($name));
```

Non-docker:
```
bool(true)
int(123)
```

Docker:
```
bool(false)
bool(false)
```

The simplest solution would be to use a safer limit for file name, such as 200, or to always use the hash.

**Comment by Gamesh** [comment] 2016-12-09 07:09
there is even a problem when adding files to tar, for example you warm-up a cache and archive it for deployment
```
tar-based phar "/tmp/archive584a56835cf9f.tar" cannot be created, filename "var/cache/dev/annotations/01/5b49747576735c4f726d42756e646c655c456e746974795c52756c6c73247573657269
  64405b416e6e6f745d5d5b315d.doctrinecache.data" is too long for tar file format
```

**Comment by J7mbo** [comment] 2016-12-13 13:13
I have the same issue, except it's for prod too.

**Comment by acasademont** [comment] 2017-01-02 18:50
same here with ubuntu 16.04

**Comment by charlycoste** [comment] 2017-01-03 09:19
Same on Ubuntu 14.04 and PHP 5.5.9

**Comment by acasademont** [comment] 2017-01-03 09:31
Question, why don't we always use the already computed hash and we solve the problem for all platforms?

**Comment by Tobion** [comment] 2017-01-19 10:20
@acasademont I agree. See discussion in https://github.com/doctrine/cache/pull/94#r41714634

**Comment by acasademont** [comment] 2017-01-19 11:52
@Tobion seriously? A condition to check for the uniqueness of a SHA256? This is crazy! The person who finds a collision will become instantly famous (and earn some good money), the world hasn't still found a collision on SHA1 :/

@Ocramius can we please reconsider this?

**Comment by acasademont** [comment] 2017-08-01 20:19
ping @Ocramius, happy to work on a PR using the hash as the name, that should be more than enough to solve all these problems

**Comment by lcobucci** [comment] 2017-08-02 20:14
@acasademont please send us the PR but don't forget about the tests 😉

**Comment by emudojo** [comment] 2017-09-30 23:13
I'm having this issue also on prod using docker, can update code only containers as cache fails to be added. Any progress on this?

**Comment by jstuhli** [comment] 2017-10-01 06:03
It's fascinating how long it takes to revert one commit. 
@emudojo we've switched docker from aufs storage driver to overlay2, that should fix your issues.

**Comment by kitingChris** [comment] 2017-10-02 07:00
I have the very same issue under Ubuntu 17.04 with encrypted filesystem.

**Comment by emudojo** [comment] 2017-10-02 14:12
@jstuhli mind sharing your daemon.json to try it ?

**Comment by jstuhli** [comment] 2017-10-03 09:24
@emudojo 
`{
  "storage-driver": "overlay2"
}`
https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/

**Comment by inverse** [comment] 2017-10-09 14:38
@kitingChris did you ever solve this?

**Comment by kitingChris** [comment] 2017-10-09 15:56
@inverse since the last seven days this issue occurred? Nope! 

My only workaround was to move the whole project to a non encrypted place on my laptop which is quite annoying.... -.-

**Comment by janvernieuwe** [comment] 2018-03-02 11:51
This issue still exists on Ubuntu 16.04 LTS with an encrypted drive, my whole disk is encrypted, so i cannot even move it to an unencrypted location on the hdd.

**Comment by Hast** [comment] 2018-07-02 15:32
I have the same issue with an encrypted home directory on Mint 18.3

**Comment by digitall-it** [comment] 2018-07-02 15:39
@hast did you try my code or @janvernieuwe suggestion to symlink your cache dir to /tmp?

**Comment by Hast** [comment] 2018-07-03 12:03
@digitall-it yes, both work, but it'd be much better if there were native support for the encrypted folders.

**Comment by alcaeus** [comment] 2021-05-21 06:19
Closing as we're sunsetting this library. Please see #354 for more details.

**Closed by alcaeus** 2021-05-21 06:19 UTC
