### ISSUE TITLE
SonarQube Blocker Bug

### ISSUE THREAD

**Issue by joan16v** [doctrine/cache#397] opened 2022-03-15 08:25 UTC
SonarQube detects as a "Blocker Bug", this line in Psr6/CacheAdapter.php (Line 43):

`return $this->pool;`

Also this line in Psr6/DoctrineProvider.php (Line 39):

`return $this->provider;`

SonarQube says 'Remove this use of "$this".'

**Comment by greg0ire** [comment] 2022-03-15 09:04
@joan16v what version are you using?

**Comment by joan16v** [comment] 2022-03-15 10:21
As I can see in the last version of those classes (CacheAdapter.php and DoctrineProvider.php), those "$this" calls inside static methods are still there.

**Comment by greg0ire** [comment] 2022-03-15 10:24
There is even a phpcs ignore rule: https://github.com/doctrine/cache/blob/331b4d5dbaeab3827976273e9356b3b453c300ce/lib/Doctrine/Common/Cache/Psr6/CacheAdapter.php#L46

It was introduced in https://github.com/doctrine/cache/pull/367

Note that this closure gets bound to an object right after that: https://github.com/doctrine/cache/blob/331b4d5dbaeab3827976273e9356b3b453c300ce/lib/Doctrine/Common/Cache/Psr6/CacheAdapter.php#L50

So… what's the issue?

**Comment by joan16v** [comment] 2022-03-15 10:33
The issue is still there, and SonarQube marks it as a "Blocker Bug".

![image](https://user-images.githubusercontent.com/1021553/158359040-016baddd-4ca2-490c-842a-78930a78844a.png)

**Comment by greg0ire** [comment] 2022-03-15 10:41
> The issue is still there

I don't expect it to magically vanish.

> SonarQube marks it as a "Blocker Bug".

That's the type of issue, but it does not explain what the issue is. Also, why are you analyzing your vendor files (which, in this instance, are not broken and you cannot fix)? And finally, why should we fix issues with a tool we do not use?

**Comment by derrabus** [comment] 2022-03-15 10:43
This is a false positive. The code in question works perfectly fine.

Thank you for running a static analyzer on our codebase, but as long as this "blocker bug" does not cause any unwanted behavior, there's nothing to fix on our side. Feel free to report this issue to SonarCube, though.

Closing because this is not a bug.

**Closed as completed by derrabus** 2022-03-15 10:43 UTC
