### ISSUE TITLE
Are Ramsey\Uuid's compatible with PhpFileCache?

### ISSUE THREAD

**Issue by flaushi** [doctrine/cache#287] opened 2018-11-08 22:50 UTC
Hi,
my entities use [Ramsey\Uuid](https://github.com/ramsey/uuid) as identity field.
Now I want to use the Second level cache, and tried to use a PhpFilesCache.

I get this error :
```
Attempted to call an undefined method named "__set_state" of class "Ramsey\Uuid\Uuid".
```
My entities look roughly like
```
/** @ORM\Entity()
 * @ORM\Cache(usage="NONSTRICT_READ_WRITE")
 */
class DataCategory
{
    /**
     * @var UuidInterface
     *
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     */
    protected $id;

    public function __construct() {
        $this->id = Uuid::uuid4();
    }
```
Any my symfony config is
```
    orm:
        second_level_cache:
            region_cache_driver:
                type: service
                id: doctrine_slc_cache
            log_enabled:          true
            region_lifetime:      86400
            enabled:              true
    # service definition
    doctrine_slc_cache:
        class: Doctrine\Common\Cache\PhpFileCache
        arguments: [ '%kernel.cache_dir%/doctrine/orm/slc' ]
```
**However,** if I use a FilesystemCache instead, it does work...!! I use PHP 7.1

**Comment by Ocramius** [comment] 2018-11-08 22:56
Most likely due to the fact that the `PhpFileCache` can't deal with nested structures when the top level has `__set_state` defined.

See https://github.com/doctrine/cache/blob/36c114783b9f30abfd1054e59c28e6e2e8152481/lib/Doctrine/Common/Cache/PhpFileCache.php#L87-L93

**Comment by Ocramius** [comment] 2018-11-08 22:57
@doctrine/doctrinecore does that `var_export()` still make any sense? I'd probably rather use the `else` block at all times...

**Comment by Ocramius** [comment] 2018-11-08 22:58
Test case to reproduce this is something like::

```php
class A
{
    public $b;
    public function __set_state(){}
}
class B {}

$a = new A;
$a->b = new B;

$cache->set('foo', $a);

$cache->get('foo');
```

**Comment by flaushi** [comment] 2018-11-09 11:20
Would it help me to just store the uuid as string instead of a `Uuid`object? So, I think ti would come down to define it 

```
/**
     * @var string
     *
     * @ORM\Id
     * @ORM\Column(type="string", length=36, unique=true)
     */
    protected $id;

    public function __construct() {
        $this->id = Uuid::uuid4()->toString();
    }

**Comment by Ocramius** [comment] 2018-11-10 02:11
> The whole point of the PhpFileCache is to make the cache opcacheable. If you always use serialize, then you can just as well use the FilesystemCache.

The stored string would be opcacheable anyway, just no aggressive optimisations.

**Comment by Ocramius** [comment] 2018-11-10 02:11
@flaushi that's a workaround, the issue still stands

**Comment by stof** [comment] 2021-05-17 12:57
Closing this issue as the library is being sunset (see #354)

**Closed by stof** 2021-05-17 12:57 UTC
Labels: Bug
