### ISSUE TITLE
Updates for accepted PSR-6 standard

### ISSUE THREAD

**Issue by scaytrase** [doctrine/cache#131] opened 2015-12-29 19:06 UTC
[PSR-6](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-6-cache.md) have been approved recently. Any plans on updating the cache libraries?

PSR-6 covers the following interfaces as single one

* Cache
* ClearableCache
* FlushableCache
* MultiGetCache

https://github.com/php-fig/cache

**Comment by Ocramius** [comment] 2015-12-29 19:10
Duplicate of #119

**Closed by Ocramius** 2015-12-29 19:10 UTC
