### ISSUE TITLE
Broken php 5.6 support in minor version

### ISSUE THREAD

**Issue by unglud** [doctrine/cache#228] opened 2017-07-25 11:37 UTC
Hi!
Let me understand how it works. Minor version update should not break back compatibility, should it? And since we have
```
doctrine/common  v2.7.3          requires  doctrine/cache (1.*)
doctrine/orm     v2.5.6          requires  doctrine/cache (~1.4)
```
means, project just collapse in php 5.6. Is there a way for me to be safe in feature?
Thank you.

**Comment by alcaeus** [comment] 2017-07-25 11:39
@unglud composer will not upgrade to 1.7.0 if dependencies are not fulfilled. So, if you run `composer update` on PHP 5.6, it will install the latest version compatible with that PHP version, which would be 1.6.2.

**Comment by Ocramius** [comment] 2017-07-25 11:42
Closing as `invalid`. The tests install on 5.* just fine

**Comment by unglud** [comment] 2017-07-25 11:42
@alcaeus tell this to my dead project ))
```
doctrine/cache (1.*) - means >=1 && < 2
doctrine/cache (~1.4) - means >=1 && < 2
```
Am I right?

**Closed by Ocramius** 2017-07-25 11:42 UTC
Labels: question

**Comment by Ocramius** [comment] 2017-07-25 11:44
Correct. Next minor of doctrine/cache needs 7.1

**Comment by unglud** [comment] 2017-07-25 11:47
![but....](https://i.imgflip.com/oyd5a.jpg?a416880)

**Comment by alcaeus** [comment] 2017-07-25 11:49
@unglud not sure what the problem is. Yes, the next minor version will require PHP 7.1. No, that is not considered a BC break: we're dropping support for a PHP version that is no longer getting releases.
If your project is dead you most likely ran `composer update` on PHP 7.1 while running the code on PHP 5.6. That's your fault, not ours.

**Comment by unglud** [comment] 2017-07-25 11:51
I never say it's your fault, I just was surprised to have broken project on minor update. Now I wander what else packages can bring me something similar.

**Comment by alcaeus** [comment] 2017-07-25 11:54
You have a broken project because your environment is not set up properly, not because of a minor upgrade. Let me repeat: `composer update` will not install 1.7 unless you're running it on PHP 7.1. If you're running it on PHP 5.6, it will install 1.6.2. I suppose you see the problem with running `composer update` on 7.1 then deploying to 5.6, right?

**Comment by unglud** [comment] 2017-07-25 11:56
@alcaeus yeah, thank you for explanations. Now I get it. And sorry I ask somehow wrong.

**Comment by alcaeus** [comment] 2017-07-25 11:57
That's alright - let's just say you're not the first person to have this problem this week and it has always been the same cause.
