### ISSUE TITLE
Not working with symfony/cache v 6.1.1

### ISSUE THREAD

**Issue by Selion05** [doctrine/cache#408] opened 2022-06-13 16:51 UTC
I am migrating to symfony 6 and bumped into this. 

> Fatal error: Uncaught Error: Class "Symfony\Component\Cache\DoctrineProvider" not found

Seems like the class was deprecated in symfony/cache 5.4 already https://github.com/symfony/cache/blob/5.4/DoctrineProvider.php

composer show symfony/cache
name     : symfony/cache
descrip. : Provides an extended PSR-6, PSR-16 (and tags) implementation
keywords : caching, psr6
versions : * v6.1.1

composer show doctrine/cache
name     : doctrine/cache
descrip. : PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
keywords : abstraction, apcu, cache, caching, couchdb, memcached, php, redis, xcache
versions : * 2.2.0

**Comment by stof** [comment] 2022-06-13 16:57
Can you share the stack trace ?

**Comment by Selion05** [comment] 2022-06-13 17:27
$ APP_ENV=prod bin/console assets:install


> Fatal error: Uncaught Error: Class "Symfony\Component\Cache\DoctrineProvider" not found in /var/www/html/var/cache/prod/ContainerZx7Te0U/App_KernelProdContainer.php:740
Stack trace:
#0 /var/www/html/var/cache/prod/ContainerZx7Te0U/App_KernelProdContainer.php(704): ContainerZx7Te0U\App_KernelProdContainer->getDoctrine_Orm_DefaultEntityManagerService(false)
#1 /var/www/html/var/cache/prod/ContainerZx7Te0U/EntityManager_9a5be93.php(172): ContainerZx7Te0U\App_KernelProdContainer->ContainerZx7Te0U\{closure}(NULL, Object(ContainerZx7Te0U\EntityManager_9a5be93), 'getConfiguratio...', Array, Object(Closure))
#2 /var/www/html/var/cache/prod/ContainerZx7Te0U/EntityManager_9a5be93.php(172): Closure->__invoke(NULL, Object(ContainerZx7Te0U\EntityManager_9a5be93), 'getConfiguratio...', Array, Object(Closure))
#3 /var/www/html/vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php(52): ContainerZx7Te0U\EntityManager_9a5be93->getConfiguration()
#4 /var/www/html/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php(99): Symfony\Bridge\Doctrine\CacheWarmer\ProxyCacheWarmer->warmUp('/var/www/html/v...')
#5 /var/www/html/vendor/symfony/http-kernel/Kernel.php(577): Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp('/var/www/html/v...')
#6 /var/www/html/vendor/symfony/http-kernel/Kernel.php(767): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#7 /var/www/html/vendor/symfony/http-kernel/Kernel.php(128): Symfony\Component\HttpKernel\Kernel->preBoot()
#8 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(166): Symfony\Component\HttpKernel\Kernel->boot()
#9 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(72): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#10 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/bin/console(31): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#12 {main}
  thrown in /var/www/html/var/cache/prod/ContainerZx7Te0U/App_KernelProdContainer.php on line 740

**Comment by derrabus** [comment] 2022-06-14 09:19
Can you also please share the output of `composer show`, or even better create a small application that reproduces the problem?

**Comment by Selion05** [comment] 2022-06-14 10:04
I can not share the app where it happens but in a new app (`symfony new test-app`) with `composer req orm`

$ composer show 
> doctrine/annotations                1.13.2  Docblock Annotations Parser
doctrine/cache                      2.2.0   PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as red...
doctrine/collections                1.6.8   PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                     3.3.0   PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects ...
doctrine/dbal                       3.3.6   Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and manag...
doctrine/deprecations               v1.0.0  A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to disable all depreca...
doctrine/doctrine-bundle            2.7.0   Symfony DoctrineBundle
doctrine/doctrine-migrations-bundle 3.2.2   Symfony DoctrineMigrationsBundle
doctrine/event-manager              1.1.1   The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine p...
doctrine/inflector                  2.0.4   PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercas...
doctrine/instantiator               1.4.1   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                      1.2.3   PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                 3.5.1   PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL...
doctrine/orm                        2.12.2  Object-Relational-Mapper for PHP
doctrine/persistence                3.0.2   The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine ...
doctrine/sql-formatter              1.1.2   a PHP SQL highlighting library
friendsofphp/proxy-manager-lts      v1.0.12 Adding support for a wider range of PHP versions to ocramius/proxy-manager
laminas/laminas-code                4.5.2   Extensions to the PHP Reflection API, static code scanning, and code generation
psr/cache                           3.0.0   Common interface for caching libraries
psr/container                       2.0.2   Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                1.0.0   Standard interfaces for event handling.
psr/log                             3.0.0   Common interface for logging libraries
symfony/cache                       v6.1.1  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts             v3.1.0  Generic abstractions related to caching
symfony/config                      v6.1.0  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                     v6.1.1  Eases the creation of beautiful and testable command line interfaces
symfony/dependency-injection        v6.1.0  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts       v3.1.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge             v6.1.0  Provides integration for Doctrine with various Symfony components
symfony/dotenv                      v6.1.0  Registers environment variables from a .env file
symfony/error-handler               v6.1.0  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher            v6.1.0  Provides tools that allow your application components to communicate with each other by dispatching events an...
symfony/event-dispatcher-contracts  v3.1.0  Generic abstractions related to dispatching event
symfony/filesystem                  v6.1.0  Provides basic utilities for the filesystem
symfony/finder                      v6.1.0  Finds files and directories via an intuitive fluent interface
symfony/flex                        v2.2.1  Composer plugin for Symfony
symfony/framework-bundle            v6.1.1  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-foundation             v6.1.1  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                 v6.1.1  Provides a structured process for converting a Request into a Response
symfony/polyfill-intl-grapheme      v1.26.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer    v1.26.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring           v1.26.0 Symfony polyfill for the Mbstring extension
symfony/proxy-manager-bridge        v6.1.0  Provides integration for ProxyManager with various Symfony components
symfony/routing                     v6.1.1  Maps an HTTP request to a set of configuration variables
symfony/runtime                     v6.1.1  Enables decoupling PHP applications from global state
symfony/service-contracts           v3.1.0  Generic abstractions related to writing services
symfony/stopwatch                   v6.1.0  Provides a way to profile code
symfony/string                      v6.1.0  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a...
symfony/var-dumper                  v6.1.0  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter                v6.1.1  Allows exporting any serializable PHP data structure to plain PHP code
symfony/yaml                        v6.1.0  Loads and dumps YAML files

I think this line here is the issue
https://github.com/doctrine/cache/blob/1ca8f21980e770095a31456042471a57bc4c68fb/lib/Doctrine/Common/Cache/Psr6/CacheAdapter.php#L12


There is a DoctrineProvider in the same namespace 
https://github.com/doctrine/cache/blob/1ca8f21980e770095a31456042471a57bc4c68fb/lib/Doctrine/Common/Cache/Psr6/DoctrineProvider.php#L22-L27

which is suggested in symfony

https://github.com/symfony/cache/blob/46430ec78f7f3962021e0a1f19af08c8d2906cbf/DoctrineProvider.php#L25

**Comment by derrabus** [comment] 2022-06-14 10:42
> I think this line here is the issue
> 
> https://github.com/doctrine/cache/blob/1ca8f21980e770095a31456042471a57bc4c68fb/lib/Doctrine/Common/Cache/Psr6/CacheAdapter.php#L12

Why? You can `use` any class you want, it does not have to exist.

**Comment by derrabus** [comment] 2022-06-14 10:45
Your dependencies look good. I don't understand why `DoctrineProvider` should be used at all in your case. I'm afraid, I'll have to ask once again for a reproducer application.

see https://symfony.com/doc/current/contributing/code/reproducer.html

**Comment by garnett2125** [comment] 2022-11-30 11:02
I'm facing the same issue, @Selion05 have you found any solution ?
Thanks

**Comment by Selion05** [comment] 2022-11-30 11:20
not a good one... i added the file manually
in composer.json under  autoload.psr-4 add ` "Symfony\\Component\\Cache\\": "packages/symfony-cache-fix"`
and copy the file to `packages/symfony-cache-fix/DoctrineProvider.php`

but so far no issues with that

**Comment by garnett2125** [comment] 2022-11-30 13:19
Thanks for the feedback ! I was having this issue when clearing cache. Then I manually deleted cache directories and the error disappeared for me

**Comment by derrabus** [comment] 2022-11-30 20:31
I'm closing the issue because we still don't have a reproducer.

**Closed as not planned by derrabus** 2022-11-30 20:31 UTC
