### ISSUE TITLE
ChainCache::doFetch should not save items to previous caches without TTL

### ISSUE THREAD

**Issue by gskema** [doctrine/cache#269] opened 2018-06-04 12:28 UTC
It is not right that `ChainCache` independently decides to save found item to previous caches without TTL. E.g. saving to Redis without TTL will result in many trash records.

**Comment by Ocramius** [comment] 2018-06-04 14:25
Duplicate of https://github.com/doctrine/cache/issues/246

**Closed by Ocramius** 2018-06-04 14:25 UTC
