### ISSUE TITLE
1.12.1 and PHP7 breaking compatibility

### ISSUE THREAD

**Issue by Tithugues** [doctrine/cache#392] opened 2021-07-22 15:26 UTC
Hi,

I just noticed something strange.
Based on https://github.com/doctrine/cache/blob/1.12.1/composer.json, it seems that 1.12.1 should be ~7.1 and 8.0 compatible.
But in this version, we can also see this: https://github.com/doctrine/cache/blob/1.12.1/lib/Doctrine/Common/Cache/Psr6/TypedCacheItem.php#L24

```
    public function __construct(
        private string $key,
        private mixed $value,
        private bool $isHit,
    ) {
    }
```

But if I'm right, and based on [PHP website](https://www.php.net/releases/8.0/en.php#constructor-property-promotion), this is a PHP8 feature.

Can you please confirm that 1.12.* is not PHP7 compatible please?

Thank you.

**Comment by stof** [comment] 2021-07-22 16:15
the TypedCachedItem class is only used on PHP 8+. See https://github.com/doctrine/cache/blob/331b4d5dbaeab3827976273e9356b3b453c300ce/lib/Doctrine/Common/Cache/Psr6/CacheAdapter.php#L80-L92

So there is no issue (and the CI confirms it)

**Comment by derrabus** [comment] 2021-07-22 16:58
I'm closing the issue as explained by @stof. If you encounter a real problem with the library, please provide a reproducer.

**Comment by Tithugues** [comment] 2021-07-23 05:53
We are using Symfony, and run the following command when running the project:

```
php bin/console cache:clear
```

This command will also automatically warm up the cache, **so it will be ready before the first request**.

The point is that all the classes are parsed / cached. Thus if something is not PHP7 compatible, it breaks…

**Comment by derrabus** [comment] 2021-07-23 07:10
Symfony itself contains optional classes that require PHP 8.

Please give us an error message and steps to reproduce your problem. Without that, nobody will be able to help you.

**Comment by alcaeus** [comment] 2021-07-23 07:41
> Without that, nobody will be able to help you.

I'll clarify this: without that, nobody will be willing to help you. If there is an issue, we'll gladly fix it when provided with ways to reproduce it, but considering how widely this library is used, I'm pretty sure people would've complained if that was a real issue.

That's not to say that this couldn't break at all, but if used in the manner this is designed in, everything works fine.

**Comment by Tithugues** [comment] 2021-07-23 07:41
I saw that they rely on some classes or others regarding the PHP version ([see](https://github.com/symfony/symfony/search?q=PHP_VERSION_ID)), but I don't find anything PHP7 incompatible so far. Do you have any example please?

And here is the error:
```
> php bin/console cache:clear
ParseError {#317
  #message: "syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE)"
  #code: 0
  #file: "./vendor/doctrine/cache/lib/Doctrine/Common/Cache/Psr6/TypedCacheItem.php"
  #line: 24
  trace: {
    ./vendor/doctrine/cache/lib/Doctrine/Common/Cache/Psr6/TypedCacheItem.php:24 { …}
    Symfony\Component\ErrorHandler\DebugClassLoader->loadClass() {}
    spl_autoload_call() {}
    ./vendor/symfony/config/Resource/ClassExistenceResource.php:84 { …}
    ./vendor/symfony/dependency-injection/ContainerBuilder.php:355 { …}
    ./vendor/symfony/dependency-injection/Loader/FileLoader.php:215 { …}
    ./vendor/symfony/dependency-injection/Loader/FileLoader.php:103 { …}
    ./vendor/symfony/dependency-injection/Loader/YamlFileLoader.php:698 { …}
    ./vendor/symfony/dependency-injection/Loader/YamlFileLoader.php:255 { …}
    ./vendor/symfony/dependency-injection/Loader/YamlFileLoader.php:175 { …}
    ./vendor/symfony/dependency-injection/Loader/YamlFileLoader.php:133 { …}
    ./vendor/symfony/config/Loader/FileLoader.php:159 { …}
    ./vendor/symfony/config/Loader/FileLoader.php:98 { …}
    ./vendor/symfony/dependency-injection/Loader/FileLoader.php:66 { …}
    ./vendor/symfony/dependency-injection/Loader/YamlFileLoader.php:218 { …}
    ./vendor/symfony/dependency-injection/Loader/YamlFileLoader.php:154 { …}
    ./vendor/symfony/dependency-injection/Loader/YamlFileLoader.php:133 { …}
    ./vendor/sfynx-project/tool-ddd-bundle/src/DddBundle/SfynxDddBundle.php:25 { …}
    ./vendor/symfony/http-kernel/Kernel.php:675 { …}
    ./vendor/symfony/http-kernel/Kernel.php:646 { …}
    ./vendor/symfony/http-kernel/Kernel.php:544 { …}
    ./vendor/symfony/http-kernel/Kernel.php:786 { …}
    ./vendor/symfony/http-kernel/Kernel.php:125 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:168 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:74 { …}
    ./vendor/symfony/console/Application.php:167 { …}
    ./bin/console:43 {
      › /** @noinspection PhpUnhandledExceptionInspection */
      › (new Application(new Kernel($_SERVER['APP_ENV'], (bool)$_SERVER['APP_DEBUG'])))->run($input);
      ›
    }
  }
}
2021-07-22T16:46:13+02:00 [critical] Uncaught Error: syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE)
```

Extra information:
```
> php -v
PHP 7.4.3 (cli) (built: Jul  5 2021 15:13:35) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```

**Comment by stof** [comment] 2021-07-23 08:04
@Tithugues can you share the content of the SfynxDddBundle class ?

**Comment by Tithugues** [comment] 2021-07-23 08:11
Here is the class:
```php
<?php
declare(strict_types=1);

namespace Sfynx\DddBundle;

use Exception;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;
use Symfony\Component\HttpKernel\Bundle\Bundle;

/**
 * Class SfynxDddBundle
 *
 * @codeCoverageIgnore Bundle class can not be tested.
 */
final class SfynxDddBundle extends Bundle
{
    /**
     * @param ContainerBuilder $container
     * @throws Exception
     */
    public function build(ContainerBuilder $container): void
    {
        (new YamlFileLoader($container, new FileLocator(__DIR__ . '/Resources/config')))->load('services.yml');
        parent::build($container);
    }
}
```

**Comment by derrabus** [comment] 2021-07-23 08:25
What versions of `symfony/dependency-injection` and `symfony/config` are you using?

**Comment by Tithugues** [comment] 2021-07-23 10:30
I think that the question is tricky, because the project doesn't request these dependencies directly.

Here is the tree dependencies for both requested (please note this is the current tree when doctrine/cache 1.12.* is excluded from the allowed dependencies so our project can work again):

```
symfony/config:
-- ^4.3.3|^5.0 from doctrine/doctrine-bundle
---- ^1.11|^2.0 from doctrine/doctrine-fixtures-bundle (see origin below)

-- 3.4|^4.3|^5.0 from doctrine/doctrine-fixtures-bundle
---- ~3.4.0 from sfynx-project/tool-ddd-bundle

-- ^5.3 from symfony/framework-bundle
---- ^5.1.7 from aareon-dil/version-getter-bundle
---- 3.4.30|^4.3.3|^5.0 from doctrine/doctrine-bundle (see origin above)
---- ^5.2.6 from sfynx-project/tool-ddd-bundle
---- ^5.2.6 from sfynx-project/tool-multitenant-bundle
---- 3.0 || ^4.0 || ^5.0 from jms/serializer-bundle
------ ~3.9.1 from sfynx-project/tool-ddd-bundle

-- ~4.4 || ^5.0 from symfony/monolog-bundle
---- ~3.7.0 from sfynx-project/tool-ddd-bundle

symfony/dependency-injection:
-- ^4.3.3|^5.0 from doctrine/doctrine-bundle
---- ^1.11|^2.0 from doctrine/doctrine-fixtures-bundle
------ ~3.4.0 from sfynx-project/tool-ddd-bundle
```

I hope this is clear enough…

I'll provide later the versions retrieved by composer when 1.12.* is not excluded.

**Comment by nicolas-grekas** [comment] 2021-07-23 12:05
Please provide a small reproducing app if you want any of us to have a look.
On my side, I see no issue with this very repo, but it'd might still be good to understand where this comes from.

**Comment by Tithugues** [comment] 2021-07-23 12:50
> What versions of `symfony/dependency-injection` and `symfony/config` are you using?

I got the information. When getting composer dependencies with PHP 7.4, composer downloaded these versions:
  - Installing symfony/dependency-injection (v5.3.3): Extracting archive
  - Installing symfony/config (v5.3.3): Extracting archive

I'm currently trying to provide a repository to reproduce the error.

**Comment by stof** [comment] 2021-07-23 12:52
@Tithugues to show the version of packages installed in a project, use `composer show --installed`

**Comment by Tithugues** [comment] 2021-07-23 13:18
Here it is: https://github.com/Tithugues/dcbc

Using a PHP7.4, run a `composer update` and you should get the error.

Please note this configuration: https://github.com/Tithugues/dcbc/blob/main/config/services.yaml#L26

Without it, there is no error. I'll leave the technical information about this configuration to the rest of my team if you need any.

Thank you.

**Comment by nicolas-grekas** [comment] 2021-07-23 13:22
Oh, then that's the reason why. Resource discovery should not be used on directories you don't own!
This should be replaced by explicit service registration.

**Closed as completed by nicolas-grekas** 2021-07-23 13:22 UTC

**Comment by Tithugues** [comment] 2021-07-23 13:23
OK, thanks for the notice. Then we'll discuss it internally and see how to fix it.

Thank you!
